### ISSUE TITLE
Example ?

### ISSUE THREAD

**Issue by stuaxo** [perkinslr/pyHorde3D#1]
Hi,
   Would it be possible to include a couple of small examples ?

S

**Comment by perkinslr** [comment]
Probably, it's an auto-generated thin wrapper, so any of the C examples work with a little tweaking.  Basically you do 

```
from h3d import *
from glfw_h import *
```

then change the C syntax to python syntax, explicitly invoke main(), and it should just work.  
I'm working on an Object Oriented wrapper that sits on top of the thin wrapper, once that is working I'll post some examples using it.

**Comment by perkinslr** [comment]
Okay, OO wrapper is functional, with examples now available.  I'm closing this issue, if you have questions, feel free to reopen.

**Comment by stuaxo** [comment]
Awesome, I'll have a play with this :)
